[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

via_ir = true
optimizer-runs = 20_000
use_literal_content = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
