[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

optimizer = true
optimizer_runs = 100

use_literal_content = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
